version: 0.0
os: linux
files:
  # Copy frontend build directly
  - source: client/build/
    destination: /home/ssm-user/AWS-project/AWS_Project_EC2/client/build

  # Copy server code
  - source: server/
    destination: /home/ssm-user/AWS-project/AWS_Project_EC2/server

hooks:
  AfterInstall:
    - runas: ssm-user
      timeout: 300
      command: |
        cd /home/ssm-user/AWS-project/AWS_Project_EC2/server
        npm install --production

  ApplicationStart:
    - runas: ssm-user
      timeout: 60
      command: |
        cd /home/ssm-user/AWS-project/AWS_Project_EC2/server
        if pm2 list | grep -q backend; then
          pm2 restart backend --update-env
        else
          pm2 start server.js --name backend
        fi
